# Generated by Django 3.0.8 on 2020-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200708_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
